#!/bin/sh
  2 space indent
this line is too looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong
	tab indent
ok indent
        8 space indent
ok indent
    ok indent
            not ok indent
            not ok indent
    ok indent

this line has not fully quoted string "$1"/usr/bin
this line has okay variable "$1/usr/bin"
